version: '3.5'

services:
  postgres:
    image: postgres
    container_name: mercurius-postgraphile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
